twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@SonataFormatter/Form/formatter.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
        #        - '@SonataMedia/Form/media_widgets.html.twig'
#        - 'Form/media_widgets.html.twig'
